import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="pl">
			<body className={inter.className}>
				<section className="flex items-center justify-center bg-black px-4 text-white">
					{/*flex min-h-screen items-center justify-center bg-black px-4 text-white">*/}
					{children}
				</section>
				<footer>
					<p className="text-center text-sm text-amber-200">2023 &copy; Next Shop</p>
				</footer>
			</body>
		</html>
	);
}
